### PR TITLE
Add @larsoner and @GuillaumeFavelier

### PR DESCRIPTION
**Pull request by banesullivan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by banesullivan** [comment]
@larsoner and @GuillaumeFavelier, would you please review/check the dependencies here?

**Comment by banesullivan** [comment]
should `pyqt` be listed?

**Comment by larsoner** [comment]
IIRC you can use either pyqt5 or pyside2, and I'm not sure there is a way to say "you need one or the other"

**Comment by banesullivan** [comment]
@conda-forge-admin, please rerender

**Comment by banesullivan** [comment]
CI failures are unrelated / out of our control

**Comment by banesullivan** [comment]
> IIRC you can use either pyqt5 or pyside2, and I'm not sure there is a way to say "you need one or the other"

@larsoner, my general approach here is to not list any and have an import error with "hey, install one of X, Y, or Z". With that said, should there be one default here and leave the others out?

It looks like both `pyqt` and `qtpy` are listed here but not `pyside`. Should we prefer one over the other for `pyqt` or `qtpy`

**Comment by larsoner** [comment]
Perhaps we should just remove pyqt and leave qtpy in there...? @GuillaumeFavelier probably knows better than I do

**Comment by GuillaumeFavelier** [comment]
It would be nice to be close to the minimal dependencies we have in [pyvistaqt/environment.yml](https://github.com/pyvista/pyvistaqt/blob/main/environment.yml).

About Qt, `qtpy` is necessary while `pyqt` should not. If we really have to pick an implementation, I'm in favor of `pyqt` considering the results of https://github.com/pyvista/pyvistaqt/pull/136.

**Comment by banesullivan** [comment]
I just removed pyqt from the depends and as far as I can tell, the depends here should mathc that environment spec you shared. @GuillaumeFavelier, would you please approve/disapprove -- if you'd prefer me switch it to pyqt instead, let me know

**Review by GuillaumeFavelier — APPROVED** [review]
LGTM, thank you @banesullivan !

**Comment by banesullivan** [comment]
Well that lead to an error actually:

```
import: 'pyvistaqt'
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/pyvistaqt_1639669301346/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.10/site-packages/qtpy/__init__.py", line 218, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/pyvistaqt_1639669301346/test_tmp/run_test.py", line 2, in <module>
    import pyvistaqt
  File "/home/conda/feedstock_root/build_artifacts/pyvistaqt_1639669301346/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.10/site-packages/pyvistaqt/__init__.py", line 3, in <module>
    from pyvistaqt.plotting import BackgroundPlotter, MainWindow, MultiPlotter, QtInteractor
  File "/home/conda/feedstock_root/build_artifacts/pyvistaqt_1639669301346/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.10/site-packages/pyvistaqt/plotting.py", line 55, in <module>
    from qtpy import QtCore
  File "/home/conda/feedstock_root/build_artifacts/pyvistaqt_1639669301346/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.10/site-packages/qtpy/__init__.py", line 224, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

```

I'm just going to add back pyqt and not mess with this 🙃

**Pull request merged**
